apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "shortlytics-chart.fullname" . }}-db-credentials
  labels:
    app.kubernetes.io/name: backend
spec:
  refreshInterval: 1h 
  secretStoreRef:
    kind: SecretStore
    name: {{ include "shortlytics-chart.fullname" . }}-kv-store
  target:
    name: {{ include "shortlytics-chart.fullname" . }}-db-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: backend-db-username 
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: backend-db-password