apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "shortlytics-chart.fullname" . }}-kv-store
  labels:
    app.kubernetes.io/name: backend
    environment: {{ .Values.global.environment | default "dev" }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://{{ .Values.global.azure.keyVaultName }}.vault.azure.net"
      serviceAccountRef:
        name: {{ include "shortlytics-chart.fullname" . }}-backend-sa