apiVersion: v1
kind: Service
metadata:
  name: {{ include "shortlytics-chart.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}