apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shortlytics-chart.fullname" . }}-backend-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.global.azure.workloadIdentityClientId }}"
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}