apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shortlytics-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/samahmoumen/shortlytics.git'
    targetRevision: develop
    path: gitops-manifests/shortlytics 
    helm:
      releaseName: shortlytics-dev 
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shortlylics-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true