global:
  environment: dev

azure:
  keyVaultName: "shortlytics-dev-kv-3fbu" 
  workloadIdentityClientId: "60960411-2813-48cb-94f2-2889cac4bb92"

ingress:
  host: "dev.shortlytics.internal"

backend:
  image:
    tag: "579e320"
    pullPolicy: Always
  db:
    server: "shortlytics-dev-postgres" 
    name: "shortlytics-dev-db"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

frontend:
  image:
    tag: "579e320"
    pullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi 

postgres:
  database: "shortlytics-dev-db"
  storageSize: 2Gi