global:
  environment: dev
  azure:
    tenantId: "a99950fd-2582-4f30-916e-fc061b7a258b"
    keyVaultName: "shortlytics-dev-kv"
    workloadIdentityClientId: "3c073abb-501a-4416-a459-1f3444d5de78"
  imageRegistry: shortlyticsdevacrcv8h.azurecr.io
ingress:
  host: "dev.shortlytics.internal"
# Surcharge des valeurs du sous-chart Backend
backend:
  image:
    repository: shortlytics-backend
    tag: "403738e"
    pullPolicy: Always
  db:
    server: "shortlytics-dev-postgres"
    name: "shortlytics-dev-db"
  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: 250m
      memory: 384Mi
# Surcharge des valeurs du sous-chart Frontend
frontend:
  image:
    repository: shortlytics-frontend
    tag: "403738e"
    pullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
postgres:
  database: "shortlytics-dev-db"
  storageSize: 2Gi