global:
  environment: dev
  azure:
    tenantId: "a99950fd-2582-4f30-916e-fc061b7a258b"
    keyVaultName: "shortlytics-dev-kv"
    workloadIdentityClientId: "561d2b1f-f611-4dd7-98c6-ae872a118981"
  imageRegistry: shortlyticsdevacr52t1.azurecr.io

ingress:
  host: "dev.shortlytics.internal"

# Surcharge des valeurs du sous-chart Backend
backend:
  image:
    repository: shortlytics-backend
    tag: "5fabf64"
    pullPolicy: Always
  db:
    server: "shortlytics-dev-postgres"
    name: "shortlytics-dev-db"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

# Surcharge des valeurs du sous-chart Frontend
frontend:
  image:
    repository: shortlytics-frontend
    tag: "5fabf64"
    pullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

postgres:
  database: "shortlytics-dev-db"
  storageSize: 2Gi