apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shortlytics-chart.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: frontend
    environment: {{ .Values.global.environment | default "dev" }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "shortlytics-chart.fullname" . }}-frontend-sa
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}/shortlytics-frontend:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
             {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10